### ISSUE TITLE
Hello! Bluez-utils-compat package

### ISSUE THREAD

**Issue by karl6994** [artix-linux/world#18]
Hello Artix Linux developers! I'm a huge fan of Arch/Manjaro OpenRC & am impatiently awaiting my account on your forums to be accepted, I hope my account isn't "inappropriate" its my name with my favourite car year ('69 corvette stingray) & my birth year, its the same as the one I have on github, my friend said it might not get accepted because of that. Love what you guys are doing by providing an alternative to OpenRC!! 

I came here because I needed to ask you guys if you could make a package for me for OpenRC Arch, Bluez-utils-compat - I need this to work so that I can use QTSIXA on a non-systemD system.
I am sorry for posting this here as I assume maybe this isn't the right place to make a request for this stuff, really sorry, but I really need QTSIXA for my PS3 controllers to work which is a big part of me using Linux. Would it work with the SystemD dummy package? How is Artix's compatibility with the AUR?

**Comment by DamnWidget** [comment]
I just added `bluez-utils-compat` to our world-testing repos, it will be available in our main mirror shortly 

http://mirror1.artixlinux.org/repos/world-testing/os/x86_64/

Arch is compatible with everything in AUR that doesn't depends on systemd or can be compiled using systemd-dummy, sadly this wasn't the case, I just adopted the package as I also use the deprecated applications for my PS controllers so I don't mind to maintain it.

Regards.

**Comment by udeved** [comment]
@DamnWidget 

Why did you add a compat package?
Our bluez is compiled without systemd already.

**Comment by DamnWidget** [comment]
That's right, but the compat suffix is not for non Systemd compatibility is for compatibility with applications that require deprecated tools inside bluez.

**Comment by karl6994** [comment]
DamnWidget you have made me so happy!!! THANK YOU VERY MUCH!!! I cannot wait to try out Artix Linux!!! Please let me know once its released, that's honestly amazing & the only reason I've been stuck with SystemD!

**Comment by DamnWidget** [comment]
Artix GNU/Linux has been already released and it's fully functional, you can find all the information about it in http://artixlinux.org

**Comment by karl6994** [comment]
Awesome! I will have to install it after I shower! Cannot wait!!! 
I have to use a nonfree driver for my video card, I hope I can reach a terminal & install the nonfree driver, I wasn't able to with Antergos but I was able to with Manjaro... If I have this same problem as I did with antergos, I will write back to you here.

**Comment by karl6994** [comment]
Hey, why don't you have a listing on Distrowatch?! You should get in touch with those people, great way to speed up building your user-base!
