### ISSUE TITLE
Can't get back to previous issue I created

### ISSUE THREAD

**Issue by karl69942** [artix-linux/world#24]
Hello Artix-Linux developers, I was chatting with DamnWidget yesterday about the bluez-utils-compat package & was trying to get back to him about an issue I was having when installing Artix Linux, my account STILL hasn't been approved for the Artix Linux forums -.-' 

I have to use a nonfree NVIDIA driver because the other video drivers won't work at all.. I get an error about kernel-source, the driver installer cannot find kernel-source & it tells me to try specifying it, but I can't :( I really wanna use Artix Linux, this sucks..

**Comment by karl69942** [comment]
I have to get the video drivers installed while using the USB before I can even get Artix Linux to install :( this is really not easy.. I was able to do it on Manjaro but I can't do it on Artix...

**Comment by karl69942** [comment]
"Unable to find the kernel source tree for the currently running kernel. Please make sure you have installed the kernel source files for your kernel and that they are properly configured; on Red Hat Linux systems, for example, be sure you have the 'kernel-source' or 'kernel-devel' RPM installed. If you know the correct kernel source files are installed, you may specify the kernel source with the '--kernel-source-path' command line option.

**Comment by karl69942** [comment]
after all the trouble I went through, I decided I'd pop my harddrive into another PC & just try installing it + the video driver then popping it back into my desktop... after all that trouble I had to go through, THIS is what I get when trying to install... -.-' dissappointed doesn't even begin to express my anger. how ridiculous is this!?!?! WOW
<class 'subprocess.CalledProcessError'>
Command 'dbus-uuidgen --ensure' returned non-zero exit status 127.
Traceback:
  File "/usr/lib/calamares/modules/machineid/main.py", line 54, in run
    check_target_env_call(["dbus-uuidgen", "--ensure"])
  File "<string>", line 2, in <module>

**Comment by archnous** [comment]
I personally approved your forum account on Sept 15, have you even tried to login?

**Comment by karl69942** [comment]
I never got an activation email like the site said I would get so I didn't know. I created an issue on the forums, but even after finding a work-around for my problem I get this stupid error -.- the installer fails... every time!!! doesn't even matter what installer I use, I tried the i3 one then I tried the lxqt one and they both give me this same error as listed above.

**Comment by karl69942** [comment]
Like are you guys going to fix your ISO image or what??? This is pretty retarded, doesn't matter whether I use i3 or lxqt or whatever, I can't make this dumb shit work. 
Wasted an entire day screwing around with Artix Linux & can't even get it to install, fails every single time!

**Comment by udeved** [comment]
I am very sorry, we can't help you. We are busy producing retarded, ridiculous shit, which required our full attention, leaving us no time to help well mannered, information rich bug reports.
