### ISSUE TITLE
pulseaudio: gconf & bluetooth

### ISSUE THREAD

**Issue by physkets** [artix-linux/world#28]
Can the [extra] pacakges _pulseaudio-gconf_ and _pulseaudio-bluetooth_ be brought into the [world] repository?

Because they aren't there right now, updates lead to the _pulseaudio_ from [extra] also being pulled so as to satisfy version dependencies. This makes it skip the one in [world].

These packages do not seem to have any systemd (as far as I know), so it should just be a matter of including it. Thanks!

**Comment by physkets** [comment]
I just realised that one must technically pull-in every package that (non-optionally) depends on _pulseaudio_. Those two were just the ones that are causing me trouble. The full list is:

```
deepin-daemon
gnome-settings-daemon
gnome-settings-daemon (testing)
pavucontrol-qt
ponymix
projectm-pulseaudio
pulseaudio-alsa
pulseaudio-bluetooth
pulseaudio-equalizer
pulseaudio-gconf
pulseaudio-jack
pulseaudio-lirc
pulseaudio-zeroconf
vibe
``` 

Maybe the _pulseaudio-_ packages can be given priority, because those are the ones that get concurrent updates.

**Comment by archnous** [comment]
Pulseaudio and lib are ver.11 in world-testing since quite a few days. If
you're in such a hurry get them from there.

**Comment by physkets** [comment]
I could, but that is just a temporary solution. The same thing could happen again, if only _pulseaudio_ stays in our repos. I was just proposing a more permanent solution to a problem.
