### ISSUE TITLE
Crashy gtk3 in world repository

### ISSUE THREAD

**Issue by kozec** [artix-linux/world#42]
Hello, I'd just like to bring to your attention that gtk3 version 3.22.26+47+g3a1a7135a2-1 in world repository is prone to crashes:

```
Thread 1 "gedit" received signal SIGSEGV, Segmentation fault.
0x00007ffff2abda30 in cloud_providers_collector_get_providers () from /usr/lib/libcloudproviders.so.0
(gdb) 
```

To reproduce, run `gedit` or any other GTK3 application and get to "file->open" dialog _twice_.

[Entire stacktrace](https://paste.ee/p/SXMBY)
[More info in Arch forum](https://bbs.archlinux.org/viewtopic.php?id=232172), tldr is that their g3a1a7135a2 **-3** doesn't have the issue.

**Comment by cromerc** [comment]
Thanks for the heads up. The updated g3a1a7135a2-3 is already available in the world-testing repo and will soon be in the world repo.

**Comment by thefallenrat** [comment]
The package in question ( `gtk3-3.22.26+47+g3a1a7135a2-3`) is on world repo now, so I think this issue should be fixed by now

Closing
