### ISSUE TITLE
clang/llvm/llvm-libs a bit old in world

### ISSUE THREAD

**Issue by artixruby** [artix-linux/world#50]
ArchLinux stable repos provided clang, llvm, and llvm-libs 5.0.1-1 more than a week ago (Dec 20). May cause breakage with upcoming libx264, glibc, gcc, gcc-libs, and ffmpeg packages, in ArchLinux staging, if not in sync.

**Comment by thefallenrat** [comment]
Thank you for reporting this. llvm has been updated in `[world-testing]` repo (092d8c9) and soon be pushed into the stable repo. Sorry for the inconvenience

Thanks again!
