### ISSUE TITLE
mpv is broken due to libcdio-paranoia and libcdio being too old

### ISSUE THREAD

**Issue by artixruby** [artix-linux/world#58]
ArchLinux stable repos provide libcdio-paranoia=10.2+0.94+2-2 and libcdio=2.0.0-1. ArtixLinux world repos provide libcdio-paranoia=10.2+0.94+2-1 and libcdio=0.94-2. This un-sync unfortunately breaks mpv (currently mpv=1:0.27.0-6) and by extention gnome-mpv and baka-mplayer.

**Comment by konimex** [comment]
`libcdio-2.0.0-1` and `libcdio-paranoia-10.2+0.94+2-2` has been pushed to `[world-testing]` in commits https://github.com/artix-linux/world/commit/1edf21d263a90ea2ef876ee11e9aa57481c2d02b and https://github.com/artix-linux/world/commit/70fbb5c1b3ca44654b81e87129598d653c924309.

We'll push it to stable in the next few days. Thanks for the report!
